package ir.sobhan.sobhaneh.common.response;


public enum ErrorType {

    UNKNOWN_ERROR,

    PHONE_NUMBER_INVALID,
    PASSWORD_INVALID,
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    WRONG_PASSWORD,
    USER_NOT_LOGGED_IN,

    PORT_IN_USE_BY_ANOTHER_HOST,
    PORT_NUMBER_MUST_BE_AT_LEAST_10000,
    AT_MOST_1000_PORTS_ALLOWED,
    INVALID_PORT_RANGE,
    NO_FREE_HOST,
    INVALID_CODE,
    HOST_NOT_FOUND,

    INVALID_WORKSPACE_NAME,
    WORKSPACE_ALREADY_EXISTS,
    WORKSPACE_NOT_FOUND,
    NO_AVAILABLE_HOST,
    NO_FREE_PORT,

    INVALID_TOKEN,
    TOKEN_EXPIRED,

    USERNAME_ALREADY_EXISTS,
    INVALID_USERNAME,

    USER_NOT_IN_WORKSPACE,
    CHAT_NOT_FOUND
}